[build]
builder = "nixpacks"
buildCommand = "npm run build --workspace=@facturas/api"

[deploy]
startCommand = "npm run start --workspace=@facturas/api"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30
